#!/bin/bash

# Function to display information about a subdomain
display_info() {
    subdomain=$1
    domain=$2
    record_type=$(dig +short $subdomain.$domain | awk '{print $4}')
    destination=$(dig +short $subdomain.$domain)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if both domain and subdomain are provided
if [ $# -eq 2 ]; then
    display_info $2 $1
else
    # Display information for default subdomains
    display_info www $1
    display_info lb-01 $1
    display_info web-01 $1
    display_info web-02 $1
fi
